# 5章　pandas入門
- pandasはテーブル形式や不均衡なデータを扱うのに適している（一方NumPyは均一な数値データに適す）


In [2]:
import pandas as pd
import numpy as np

## 5.1 pandasのデータ構造
- シリーズ（Series）とデータフレーム（DataFrame）

### 5.1.1 シリーズ（Series）
- シリーズは1次元の配列のようなオブジェクト
- `pandas.Series()`に配列を渡して初期化
- 値とそのインデックスの配列
- values属性とindex属性で値とインデックスを取得できる
- 初期化時の`index`キーワード引数に配列を渡してインデックスを指定できる
- インデックスを使って値を参照できる（複数の場合はインデックスのリストを渡す）
- 条件指定フィルタリングや要素に対する演算、NumPyの関数を適用できる
- インデックスと値がマッピングされた固定長の順序付きディクショナリとみなせるので、ディクショナリの代わりになる
- Pythonのディクショナリで初期化も可能（インデックスはソートされたキー）
  - キーの順のリストを`index`キーワード引数に渡すと上書きできる
- インデックスを指定したとき値が存在しないとNan（Not a number）=欠損値となる
- `isnull`や`notnull`で欠損値を判定できる
- シリーズ同士の演算で自動で同じインデックス同士が結び付けられ整形される
- シリーズオブジェクト自身と、インデックスはname属性を持つ
- シリーズのインデックスは代入で上書きできる

### 5.1.2 データフレーム
- テーブル形式のデータ構造
- 行と列にインデックスを持つ
- シリーズを値に持つディクショナリとみなすことができる（各シリーズのインデックスを全体で共有しているイメージ）
- `pandas.DataFrame`にバリューが同じ長さのリストのディクショナリを渡して作成する
- `head`メソッドで先頭5行を取得できる
- `columnsキーワード引数に列の順番のリストを渡すと列の順番を指定できる
  - 指定した列のデータがない場合は欠損値Nanで埋まる
- 列はディクショナリ風の指定や属性指定でシリーズとして取り出すことができる
  - 属性指定はその列の名前がPythonの変数名として扱える形式の場合のみ使用できる
- 行の指定を名前でするときは`loc`属性を使う
- 列にはスカラーやndarrayで代入できる（長さが一致している必要がある）
- `Series`を列に代入することもできる
  - データフレームのインデックスと一致するように代入され、対応がなければ欠損値Nan
- 既存でない列への代入は新規列が作成される（属性指定では不可）
- delキーワードで列を削除できる
- インデックス参照による列の取得は参照ビューなので書き換えに注意する（必要ならcopyメソッドを使う）
- ディクショナリにディクショナリをネストしたものをデータフレームに渡すと、外側のキーを列、内側のキーを行として作成する
  - シリーズをバリューに持つディクショナリも同じように扱われる
- 行と列の入れ替えは転置`T`属性

### 5.1.3 インデックスオブジェクト
要再読


In [4]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
print(obj.values)
print(obj.index) # 特に指定しなければrange(4)と同じ

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
print(obj2['a'])
obj2['d'] = 6
print(obj2[['c', 'a', 'd']])

-5
c    3
a   -5
d    6
dtype: int64


In [10]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [11]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [13]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [14]:
'b' in obj2

True

In [15]:
'e' in obj2

False

In [16]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [17]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [18]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [19]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [20]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [21]:
obj3, obj4

(Ohio      35000
 Texas     71000
 Oregon    16000
 Utah       5000
 dtype: int64,
 California        NaN
 Ohio          35000.0
 Oregon        16000.0
 Texas         71000.0
 dtype: float64)

In [22]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [23]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [24]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [2]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [3]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [5]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                            index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [6]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [8]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [9]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [10]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [12]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [13]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [15]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [16]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [10]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [18]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [19]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [22]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [23]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [24]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [25]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [3]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [4]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [5]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [6]:
obj2.index is labels

True

In [11]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [12]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [14]:
'Ohio' in frame3.columns

True

In [15]:
2003 in frame3.index

False

In [17]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 5.2 pandasの重要な機能

### 5.2.1 再インデックス付け
- `reindex`メソッド：新しいインデックスを引数に、新しいオブジェクトを作成する
  - `method`オプションに`ffill`で前方に穴埋め
  - データフレームはデフォルトでは行、columnsを指定して列を再インデックス付けできる

In [3]:
# 再インデックス付け
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [5]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [6]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'b', 'c'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [7]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN

In [8]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
c      7   NaN           8

### 5.2.2 軸から要素を削除する
- `drop`メソッド
  - ラベルのシーケンスを渡して、値を削除する
  - デフォルトでは行
  - `axis=1`または`axis='colmuns'`を指定すると列
  - `inplace=True`にすると元のオブジェクトを直接書き換える

In [2]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [3]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [4]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [5]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [6]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [7]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [8]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [9]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### 5.2.3 インデックス参照、選択、フィルタリング
- 

In [18]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [19]:
obj['b']

1.0

In [17]:
obj[1]

1.0

In [20]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [21]:
obj['b'] == obj[1]

True

In [22]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [23]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [24]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [25]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [26]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [3]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [4]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [5]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [6]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [7]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [8]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [9]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### 5.2.3.1 locとilocによるデータの選択
- loc, ilocはラベルベースとインデックスベースの参照

In [10]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [12]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [13]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [14]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [15]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [16]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### 5.2.4 整数のインデックス

In [19]:
ser = pd.Series(np.arange(3.))
ser
# ser[-1] はエラーになる

0    0.0
1    1.0
2    2.0
dtype: float64

In [21]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

In [23]:
ser[:1]

0    0.0
dtype: float64

In [24]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [25]:
ser.iloc[:1]

0    0.0
dtype: float64

### 5.2.5
- インデックスが完全に対応していないオブジェクト同士の演算では、インデックスが和集合で設定され、対応がない場合には欠損値

In [26]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
                index=['a', 'c', 'e', 'f', 'g'])

In [27]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [28]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [29]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [30]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                  index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [31]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [32]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [33]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
df1

A
0  1
1  2

In [34]:
df2

B
0  3
1  4

In [35]:
df1- df2

A   B
0 NaN NaN
1 NaN NaN

#### 5.2.5.1 算術メソッドと値の置換

In [38]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [39]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [40]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [41]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [42]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [43]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [44]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### 5.2.5.2 データフレームとシリーズでの演算

In [45]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [46]:
arr[0]

array([0., 1., 2., 3.])

In [47]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [50]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]

In [49]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [51]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [52]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [53]:
series2 = pd.Series(range(3), index=list('bef'))
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [54]:
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [55]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [56]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 5.2.6 関数の適用とマッピング

In [2]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.288820 -0.749336 -0.095425
Ohio    0.038835 -0.151915 -0.782187
Texas   0.914094  0.123945  2.930038
Oregon -2.538811 -1.195659  0.338059

In [3]:
np.abs(frame)

b         d         e
Utah    0.288820  0.749336  0.095425
Ohio    0.038835  0.151915  0.782187
Texas   0.914094  0.123945  2.930038
Oregon  2.538811  1.195659  0.338059

In [4]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    3.452905
d    1.319604
e    3.712225
dtype: float64

In [5]:
frame.apply(f, axis='columns')

Utah      0.653911
Ohio      0.821023
Texas     2.806093
Oregon    2.876870
dtype: float64

In [8]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -2.538811 -1.195659 -0.782187
max  0.914094  0.123945  2.930038

In [11]:
frmt = lambda x: '%.2f' % x
frame.applymap(frmt)

b      d      e
Utah    -0.29  -0.75  -0.10
Ohio     0.04  -0.15  -0.78
Texas    0.91   0.12   2.93
Oregon  -2.54  -1.20   0.34

In [12]:
frame['e'].map(frmt)

Utah      -0.10
Ohio      -0.78
Texas      2.93
Oregon     0.34
Name: e, dtype: object

### 5.2.7 ソートとランク

In [2]:
obj = pd.Series(range(4), index=list('dabc'))
obj

d    0
a    1
b    2
c    3
dtype: int64

In [3]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [6]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=list('dabc'))
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [9]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [10]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [2]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [3]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [4]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [5]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [6]:
frame.sort_values(by=['a', 'b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [7]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [8]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [9]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [11]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [12]:
frame.rank(axis='columns')

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

### 5.2.8 重複したラベルを持つ軸のインデックス

In [2]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [3]:
obj.index.is_unique

False

In [4]:
obj['a']

a    0
a    1
dtype: int32

In [5]:
obj['c']

4

In [7]:
df = pd.DataFrame(np.random.randn(4, 3), index=list('aabb'))
df

0         1         2
a  0.477815  0.749685  0.724324
a -1.142382  2.484224 -0.342270
b  0.108382  0.473461  1.248391
b  1.197867 -0.443979 -0.199106

In [8]:
df.loc['b']

0         1         2
b  0.108382  0.473461  1.248391
b  1.197867 -0.443979 -0.199106

## 5.3 要約統計量の集計と計算

In [4]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75, -1.3]],
                  index=list('abcd'),
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [5]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [6]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [7]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [8]:
df.idxmax()

one    b
two    d
dtype: object

In [9]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [10]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [11]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [12]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### 5.3.1 相関と共分散

In [5]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

In [7]:
returns = price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2020-09-25  0.037516  0.007283  0.022787  0.011671
2020-09-28  0.023869  0.023371  0.007795  0.013537
2020-09-29 -0.007568 -0.006490 -0.010409  0.003284
2020-09-30  0.015076  0.006036  0.014812  0.000184
2020-10-01  0.008462 -0.004767  0.010127  0.013943

In [10]:
returns['MSFT'].corr(returns['IBM'])

0.5737118351592438

In [13]:
returns['MSFT'].cov(returns['IBM'])

0.00016082630599615244

In [14]:
returns.MSFT.corr(returns.IBM)

0.5737118351592438

In [15]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.497147  0.706970  0.655762
IBM   0.497147  1.000000  0.573712  0.533822
MSFT  0.706970  0.573712  1.000000  0.782692
GOOG  0.655762  0.533822  0.782692  1.000000

In [16]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000350  0.000149  0.000232  0.000203
IBM   0.000149  0.000256  0.000161  0.000141
MSFT  0.000232  0.000161  0.000307  0.000226
GOOG  0.000203  0.000141  0.000226  0.000272

In [17]:
returns.corrwith(returns.IBM)

AAPL    0.497147
IBM     1.000000
MSFT    0.573712
GOOG    0.533822
dtype: float64

In [18]:
returns.corrwith(volume)

AAPL   -0.077252
IBM    -0.098669
MSFT   -0.055223
GOOG   -0.152530
dtype: float64

### 5.3.2 一意な値、頻度の確認、所属の確認

In [19]:
obj = pd.Series(list('cadaabbcc'))
uniques = obj.unique()
uniques

array([&#39;c&#39;, &#39;a&#39;, &#39;d&#39;, &#39;b&#39;], dtype=object)

In [20]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [21]:
pd.value_counts(obj.values, sort=False)

a    3
b    2
d    1
c    3
dtype: int64

In [22]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [23]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [24]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [26]:
to_match = pd.Series(list('cabbca'))
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [27]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [28]:
result = data.apply(pd.value_counts).fillna(0)