In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 51 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 2.77 s


## 4.1 NumPy ndarray：多次元配列オブジェクト
- N-dimensional array
- ndarrayに対する演算は要素全てに作用する

In [5]:
import numpy as np

In [6]:
data = np.random.randn(2, 3)
data

array([[-1.9524715 ,  1.08172533, -0.64788448],
       [ 0.38760526, -0.22643772, -0.10960296]])

In [8]:
data * 10

array([[-19.52471503,  10.81725332,  -6.47884484],
       [  3.87605265,  -2.26437723,  -1.0960296 ]])

In [9]:
data + data

array([[-3.90494301,  2.16345066, -1.29576897],
       [ 0.77521053, -0.45287545, -0.21920592]])

- ndarrayの特徴
  - 要素はすべて同じ型がマスト
  - shapeとdtypeという属性が要素数と型を持つ

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

### 4.1.1 ndarrayの生成

In [14]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

- ndim属性は次元を持つ

In [17]:
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.empty((2, 3, 2))

array([[[1.01855798e-312, 1.01855798e-312],
        [1.01855798e-312, 9.54898106e-313],
        [1.08221785e-312, 1.03977794e-312]],

       [[1.23075756e-312, 1.03977794e-312],
        [1.12465777e-312, 9.76118064e-313],
        [1.16709769e-312, 1.90979621e-312]]])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 4.1.2 ndarrayのデータ型

In [3]:
import numpy as np
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [5]:
arr1.dtype

dtype('float64')

In [6]:
arr2.dtype

dtype('int32')

In [8]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [12]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [4]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.2])
# arr.astype(np.int32)
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.2])

In [5]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [9]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [10]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

- astypeを呼び出すと、必ず新規ndarrayが生成される

### 4.1.3 ndarrayの算術演算
- ベクトル演算
- 同サイズのndarray同士で、同位置の要素同士の計算をする

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])