In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 51 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 2.77 s


## 4.1 NumPy ndarray：多次元配列オブジェクト
- N-dimensional array
- ndarrayに対する演算は要素全てに作用する

In [5]:
import numpy as np

In [6]:
data = np.random.randn(2, 3)
data

array([[-1.9524715 ,  1.08172533, -0.64788448],
       [ 0.38760526, -0.22643772, -0.10960296]])

In [8]:
data * 10

array([[-19.52471503,  10.81725332,  -6.47884484],
       [  3.87605265,  -2.26437723,  -1.0960296 ]])

In [9]:
data + data

array([[-3.90494301,  2.16345066, -1.29576897],
       [ 0.77521053, -0.45287545, -0.21920592]])

- ndarrayの特徴
  - 要素はすべて同じ型がマスト
  - shapeとdtypeという属性が要素数と型を持つ

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

### 4.1.1 ndarrayの生成

In [14]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

- ndim属性は次元を持つ

In [17]:
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.empty((2, 3, 2))

array([[[1.01855798e-312, 1.01855798e-312],
        [1.01855798e-312, 9.54898106e-313],
        [1.08221785e-312, 1.03977794e-312]],

       [[1.23075756e-312, 1.03977794e-312],
        [1.12465777e-312, 9.76118064e-313],
        [1.16709769e-312, 1.90979621e-312]]])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 4.1.2 ndarrayのデータ型