In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 51 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 2.77 s


## 4.1 NumPy ndarray：多次元配列オブジェクト
- N-dimensional array
- ndarrayに対する演算は要素全てに作用する

In [5]:
import numpy as np

In [6]:
data = np.random.randn(2, 3)
data

array([[-1.9524715 ,  1.08172533, -0.64788448],
       [ 0.38760526, -0.22643772, -0.10960296]])

In [8]:
data * 10

array([[-19.52471503,  10.81725332,  -6.47884484],
       [  3.87605265,  -2.26437723,  -1.0960296 ]])

In [9]:
data + data

array([[-3.90494301,  2.16345066, -1.29576897],
       [ 0.77521053, -0.45287545, -0.21920592]])

- ndarrayの特徴
  - 要素はすべて同じ型がマスト
  - shapeとdtypeという属性が要素数と型を持つ

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

### 4.1.1 ndarrayの生成

In [14]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

- ndim属性は次元を持つ

In [17]:
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.empty((2, 3, 2))

array([[[1.01855798e-312, 1.01855798e-312],
        [1.01855798e-312, 9.54898106e-313],
        [1.08221785e-312, 1.03977794e-312]],

       [[1.23075756e-312, 1.03977794e-312],
        [1.12465777e-312, 9.76118064e-313],
        [1.16709769e-312, 1.90979621e-312]]])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 4.1.2 ndarrayのデータ型

In [2]:
import numpy as np
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [5]:
arr1.dtype

dtype('float64')

In [6]:
arr2.dtype

dtype('int32')

In [8]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [12]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [4]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.2])
# arr.astype(np.int32)
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.2])

In [5]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [9]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [10]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

- astypeを呼び出すと、必ず新規ndarrayが生成される

### 4.1.3 ndarrayの算術演算
- ベクトル演算
- 同サイズのndarray同士で、同位置の要素同士の計算をする

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [6]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [8]:
arr * 0.5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [10]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [11]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### 4.1.4 インデックス参照とスライシングの基礎

In [12]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[5]

5

In [15]:
arr[5:8]

array([5, 6, 7])

In [16]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

- pythonのリストとnumpyの多次元配列との相違点
  - スライスが元のndarrayのビューであり、コピーではなく、あらうる変更が反映される 
  - コピーしたいときは明示的にcopyメソッドを使う

In [19]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [21]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [22]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [23]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2] 

array([7, 8, 9])

In [24]:
arr2d[0][2]

3

In [26]:
arr2d[0, 2]

3

In [35]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
arr3d[1, 0]

array([7, 8, 9])

In [40]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [41]:
x[0]

array([7, 8, 9])

#### 4.1.4.1 スライスによるインデックス参照

In [42]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [43]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [44]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [48]:
arr2d[1, :2]

array([4, 5])

In [49]:
arr2d[:2, 2]

array([3, 6])

In [50]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [51]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 4.1.5 ブールインデックス参照

In [2]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [3]:
data

array([[-1.23158139,  0.2742528 ,  0.54807465, -0.7925238 ],
       [-0.72509897,  1.48056094,  0.51985078,  0.24312531],
       [ 1.29321503,  1.57811741,  1.61600684,  0.23936508],
       [ 0.24524239,  0.23244114,  1.57630123, -1.34026396],
       [ 0.97814298, -0.52215465,  1.28358953,  0.86055294],
       [ 0.37888972, -1.0464174 , -0.25553428, -1.20428012],
       [ 0.01305448,  1.06426369,  1.34508784, -1.93762907]])

In [4]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [5]:
data[names == 'Bob']

array([[-1.23158139,  0.2742528 ,  0.54807465, -0.7925238 ],
       [ 0.24524239,  0.23244114,  1.57630123, -1.34026396]])

In [6]:
data[names == 'Bob', 2:]

array([[ 0.54807465, -0.7925238 ],
       [ 1.57630123, -1.34026396]])

In [8]:
data[names == 'Bob', 3]

array([-0.7925238 , -1.34026396])

In [9]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [10]:
data[~(names == 'Bob')]

array([[-0.72509897,  1.48056094,  0.51985078,  0.24312531],
       [ 1.29321503,  1.57811741,  1.61600684,  0.23936508],
       [ 0.97814298, -0.52215465,  1.28358953,  0.86055294],
       [ 0.37888972, -1.0464174 , -0.25553428, -1.20428012],
       [ 0.01305448,  1.06426369,  1.34508784, -1.93762907]])

In [11]:
cond = names == 'Bob'
data[~cond]

array([[-0.72509897,  1.48056094,  0.51985078,  0.24312531],
       [ 1.29321503,  1.57811741,  1.61600684,  0.23936508],
       [ 0.97814298, -0.52215465,  1.28358953,  0.86055294],
       [ 0.37888972, -1.0464174 , -0.25553428, -1.20428012],
       [ 0.01305448,  1.06426369,  1.34508784, -1.93762907]])

In [12]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [13]:
data[mask]

array([[-1.23158139,  0.2742528 ,  0.54807465, -0.7925238 ],
       [ 1.29321503,  1.57811741,  1.61600684,  0.23936508],
       [ 0.24524239,  0.23244114,  1.57630123, -1.34026396],
       [ 0.97814298, -0.52215465,  1.28358953,  0.86055294]])

- ブールインデックス参照による抽出は元データのコピーが生成される点に注意
- 真偽値配列にはpythonのand/orキーワードは使用できない

In [14]:
data[data < 0] = 0

In [15]:
data

array([[0.        , 0.2742528 , 0.54807465, 0.        ],
       [0.        , 1.48056094, 0.51985078, 0.24312531],
       [1.29321503, 1.57811741, 1.61600684, 0.23936508],
       [0.24524239, 0.23244114, 1.57630123, 0.        ],
       [0.97814298, 0.        , 1.28358953, 0.86055294],
       [0.37888972, 0.        , 0.        , 0.        ],
       [0.01305448, 1.06426369, 1.34508784, 0.        ]])

In [17]:
data[names != 'Joe'] = 7
data

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

### 4.1.6 ファンシーインデックス参照
- インデックス参照に整数配列を用いる方法
- 整数配列＝pythonの整数のリストっぽい
- コピーを返す

In [2]:
import numpy as np
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [3]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [5]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [6]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [8]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [13]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 4.1.7 転置行列、行と列の入れ替え